version: '3.8'
services:
  soldimet-app-front:
    image: node:14
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 4G
    ports:
      - '9060:9060'
      - '9000:9000'
      - '8081:8081'
      - '4200:4200'
      - '3001:3001'
    volumes:
      - ../..:/home/node/app
    working_dir: /home/node/app
    command: "yarn start"
  soldimet-app-back:
    image: back-end-local:v1
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 4G
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=dev,no-liquibase,api-docs'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
      - JHIPSTER_METRICS_LOGS_ENABLED=false
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://soldimet-mysql:3306/soldimet?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - '80:80'
    volumes:
      - ../..:/home/soldimet
      - ${HOME}/.m2:/root/.m2
    command: "mvn"
    depends_on:
      soldimet-mysql:
        condition: service_healthy
  soldimet-mysql:
    image: 'mysql:8.0.17'
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 1G
    environment:
      MYSQL_DATABASE: 'Soldimet'
      MYSQL_ROOT_PASSWORD: 'manu'
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql:
