FROM docker.elastic.co/logstash/logstash-oss:7.9.3

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-output-loggly
