version: '2'
services:
  soldimet-app:
    image: soldimet
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=qa,swagger
      # - SPRING_PROFILES_ACTIVE
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      # - SPRING_DATASOURCE_URL=jdbc:mysql://soldimet-mysql:3306/Soldimet?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      - JHIPSTER_SLEEP=5 # gives time for other services to boot before the application
    ports:
      - 80:80
    depends_on:
      - soldimet-mysql
  soldimet-mysql:
    extends:
      file: mysql.yml
      service: soldimet-mysql
