# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0034_add_spain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=False),
        ),
    ]
