apiVersion: v1
kind: Service
metadata:
  name: soldimet
  namespace: default
  labels:
    app: soldimet
spec:
  selector:
    app: soldimet
  type: NodePort
  ports:
    - name: http
      port: 80
    - name: mysql
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: soldimet-lb
spec:
  selector:
    app: soldimet
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: soldimet-console
  namespace: default
  labels:
    app: soldimet-console
spec:
  selector:
    app: soldimet-console
  type: NodePort
  ports:
    - name: kibana
      port: 5601
    - name: logstash
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: soldimet-console-lb
spec:
  selector:
    app: soldimet-console
  ports:
    - port: 5601
      targetPort: 5601
  type: LoadBalancer
